PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzUyMzc0NzAyLCJleHAiOjE3NTI0MTc5MDJ9.v1jilJF2jVQberxpFlZXgBg5sdEBHjfhwZKi4JYVsUs

{
  "novaSenha": "minhaNovaSenhaSegura123"
}